### GET request to example server
GET localhost:8080/place

###

GET localhost:8080/place/1

###

POST localhost:8080/place/create
Content-Type: application/json

{
  "name": "afasf",
  "userId": 1,
  "categoryId": 2
}

###

PUT localhost:8080/place/update/1
Content-Type: application/json

{
  "name": "updated",
  "categoryId": 2
}

###

DELETE localhost:8080/place/delete/1

###

GET localhost:8080/place/categories