### GET request to example server
GET localhost:8080/place-details/place-id/7

###

POST localhost:8080/place-details/create/4
Content-Type: application/json

{
  "description": "sdfbsf 7",
  "activites": "dsbfsdf 7",
  "address": "dfsdbsbdf 7",
  "country": "ddsfbsb 7",
  "location": "dfsdbfb 7"
}

###


PUT localhost:8080/place-details/update/7
Content-Type: application/json

{
  "description": "sdfbsf update",
  "activites": "dsbfsdfb update",
  "address": "dfsdbsbdf update",
  "country": "ddsfbsb update",
  "location": "dfsdbfb update"
}

###

DELETE localhost:8080/place-details/delete/7